apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services.staging
  namespace: feedback
spec:
  project: feedback-services
  source:
    repoURL: https://github.com/bhatvinay7/feedback.git 
    targetRevision: staging
    path: Helm/chart.staging/services
    helm:
    valueFiles:
      - values.staging.yml
    directory:
      recurse: true    
  destination:
      server: https://kubernetes.default.svc
      namespace: feedback-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true   
  