apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-cluster
  namespace: feedback
spec:
  project: kafka-services
  source:
    repoURL: https://github.com/bhatvinay7/feedback.git
    targetRevision: staging
    path:  Helm/chart.staging/kafka-cluster
    directory:
      recurse: true    
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true    