apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reach-ws-server
  namespace: feedback
spec:
  project: reach-ws-server
  source:
    repoURL: https://github.com/bhatvinay7/feedback.git 
    targetRevision: staging
    path: Helm/chart.staging/services/reach-ws-server
    helm:
      valueFiles:
        - values.staging.yml
    directory:
      recurse: true    
  destination:
      server: https://kubernetes.default.svc
      namespace: feedback-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true   
  