apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consumer1
  namespace: feedback
spec:
  project: consumer1
  source:
    repoURL: https://github.com/bhatvinay7/feedback.git 
    targetRevision: staging
    path: Helm/chart.staging/services/reach-consumer1
    helm:
      valueFiles:
        - values.staging.yml   
  destination:
      server: https://kubernetes.default.svc
      namespace: feedback-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true   
  